// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: echo.proto

#include "echo.pb.h"
#include "echo.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace echo {

static const char* Echo_method_names[] = {
  "/echo.Echo/UnaryEcho",
  "/echo.Echo/ServerStreamingEcho",
  "/echo.Echo/ClientStreamingEcho",
  "/echo.Echo/BidirectionalStreamingEcho",
};

std::unique_ptr< Echo::Stub> Echo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Echo::Stub> stub(new Echo::Stub(channel, options));
  return stub;
}

Echo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UnaryEcho_(Echo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ServerStreamingEcho_(Echo_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ClientStreamingEcho_(Echo_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_BidirectionalStreamingEcho_(Echo_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status Echo::Stub::UnaryEcho(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::echo::EchoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::echo::EchoRequest, ::echo::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnaryEcho_, context, request, response);
}

void Echo::Stub::async::UnaryEcho(::grpc::ClientContext* context, const ::echo::EchoRequest* request, ::echo::EchoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::echo::EchoRequest, ::echo::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnaryEcho_, context, request, response, std::move(f));
}

void Echo::Stub::async::UnaryEcho(::grpc::ClientContext* context, const ::echo::EchoRequest* request, ::echo::EchoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnaryEcho_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::echo::EchoResponse>* Echo::Stub::PrepareAsyncUnaryEchoRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::echo::EchoResponse, ::echo::EchoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnaryEcho_, context, request);
}

::grpc::ClientAsyncResponseReader< ::echo::EchoResponse>* Echo::Stub::AsyncUnaryEchoRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnaryEchoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::echo::EchoResponse>* Echo::Stub::ServerStreamingEchoRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::echo::EchoResponse>::Create(channel_.get(), rpcmethod_ServerStreamingEcho_, context, request);
}

void Echo::Stub::async::ServerStreamingEcho(::grpc::ClientContext* context, const ::echo::EchoRequest* request, ::grpc::ClientReadReactor< ::echo::EchoResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::echo::EchoResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ServerStreamingEcho_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::echo::EchoResponse>* Echo::Stub::AsyncServerStreamingEchoRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::echo::EchoResponse>::Create(channel_.get(), cq, rpcmethod_ServerStreamingEcho_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::echo::EchoResponse>* Echo::Stub::PrepareAsyncServerStreamingEchoRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::echo::EchoResponse>::Create(channel_.get(), cq, rpcmethod_ServerStreamingEcho_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::echo::EchoRequest>* Echo::Stub::ClientStreamingEchoRaw(::grpc::ClientContext* context, ::echo::EchoResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::echo::EchoRequest>::Create(channel_.get(), rpcmethod_ClientStreamingEcho_, context, response);
}

void Echo::Stub::async::ClientStreamingEcho(::grpc::ClientContext* context, ::echo::EchoResponse* response, ::grpc::ClientWriteReactor< ::echo::EchoRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::echo::EchoRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_ClientStreamingEcho_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::echo::EchoRequest>* Echo::Stub::AsyncClientStreamingEchoRaw(::grpc::ClientContext* context, ::echo::EchoResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::echo::EchoRequest>::Create(channel_.get(), cq, rpcmethod_ClientStreamingEcho_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::echo::EchoRequest>* Echo::Stub::PrepareAsyncClientStreamingEchoRaw(::grpc::ClientContext* context, ::echo::EchoResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::echo::EchoRequest>::Create(channel_.get(), cq, rpcmethod_ClientStreamingEcho_, context, response, false, nullptr);
}

::grpc::ClientReaderWriter< ::echo::EchoRequest, ::echo::EchoResponse>* Echo::Stub::BidirectionalStreamingEchoRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::echo::EchoRequest, ::echo::EchoResponse>::Create(channel_.get(), rpcmethod_BidirectionalStreamingEcho_, context);
}

void Echo::Stub::async::BidirectionalStreamingEcho(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::echo::EchoRequest,::echo::EchoResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::echo::EchoRequest,::echo::EchoResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_BidirectionalStreamingEcho_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::echo::EchoRequest, ::echo::EchoResponse>* Echo::Stub::AsyncBidirectionalStreamingEchoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::echo::EchoRequest, ::echo::EchoResponse>::Create(channel_.get(), cq, rpcmethod_BidirectionalStreamingEcho_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::echo::EchoRequest, ::echo::EchoResponse>* Echo::Stub::PrepareAsyncBidirectionalStreamingEchoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::echo::EchoRequest, ::echo::EchoResponse>::Create(channel_.get(), cq, rpcmethod_BidirectionalStreamingEcho_, context, false, nullptr);
}

Echo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Echo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Echo::Service, ::echo::EchoRequest, ::echo::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Echo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::echo::EchoRequest* req,
             ::echo::EchoResponse* resp) {
               return service->UnaryEcho(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Echo_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Echo::Service, ::echo::EchoRequest, ::echo::EchoResponse>(
          [](Echo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::echo::EchoRequest* req,
             ::grpc::ServerWriter<::echo::EchoResponse>* writer) {
               return service->ServerStreamingEcho(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Echo_method_names[2],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< Echo::Service, ::echo::EchoRequest, ::echo::EchoResponse>(
          [](Echo::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::echo::EchoRequest>* reader,
             ::echo::EchoResponse* resp) {
               return service->ClientStreamingEcho(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Echo_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Echo::Service, ::echo::EchoRequest, ::echo::EchoResponse>(
          [](Echo::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::echo::EchoResponse,
             ::echo::EchoRequest>* stream) {
               return service->BidirectionalStreamingEcho(ctx, stream);
             }, this)));
}

Echo::Service::~Service() {
}

::grpc::Status Echo::Service::UnaryEcho(::grpc::ServerContext* context, const ::echo::EchoRequest* request, ::echo::EchoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Echo::Service::ServerStreamingEcho(::grpc::ServerContext* context, const ::echo::EchoRequest* request, ::grpc::ServerWriter< ::echo::EchoResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Echo::Service::ClientStreamingEcho(::grpc::ServerContext* context, ::grpc::ServerReader< ::echo::EchoRequest>* reader, ::echo::EchoResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Echo::Service::BidirectionalStreamingEcho(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::echo::EchoResponse, ::echo::EchoRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace echo

